name: ecommerceapp
description: "A new Flutter project."

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.10




# icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8


#state management
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Black.ttf

